name: isp
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - pip
  - pip:
    - deepspeech==0.9.3
    - jiwer==3.0.*
    - jupyterlab==3.6.*
    - librosa==0.9.2
    - matplotlib==3.4.*
    - numpy==1.19.5
    - pandas==1.4.*
    - scipy==1.6.*
    - seaborn==0.11.*
